routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::resource('categories', 'CategoryController');
Route::resource('products','ProductController');
Route::resource('orders','OrderController');
Route::resource('orderdetails','OrderDetailController');

Route::get('/', function () { 
    return view('welcome');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    // Right all which one kor ban
    // protected $gurde=[' '];
    protected $fillable = [
        'name',
        'description'
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use App\Category;
use RealRashid\SweetAlert\Facades\Alert;




class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        if (session()->get('success')) {
            Alert::success('Success!');
        }
         if (request()->has('search')) {
             $search = request()->input('search');
             $categories = Category::where('name','like','%'.$search.'%')
                                    ->orderBy('name','DESC')
                                    ->paginate();
             return view('categories.result')->with('categories', $categories);
         }
         else{
            $categories = Category::orderBy('id', 'DESC')
                                    ->paginate(5);
            return view('categories.lists', compact('categories'));
         }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validat = $request->validate([
            'name' => 'required|unique:categories|max:150',
            'description' => 'required|max:255',
        ]);
        Category::create($validat);
        return redirect()->route('categories.index')->with('success','You complete successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = Category:: findOrFail($id);
        return view('categories.showdata', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category:: findOrFail($id);
        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $validat = $request->validate([
            'name' => 'required|max:150',
            'description' => 'max:255',
        ]);
        Category::where('id',$id)->update($validat);
        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Reguest $reguest)
    {
        Category::where('id',$reguest->id)->delete();
        return redirect()->route('categories.index');
    }
}

resources/views/categories/create.blade.php
@extends('layouts.master')
@section('title', 'category')
@section('content','Create category')
@section('big-content','home')

@section('header-content')
<div class="row">
    <div class="col-md-6">
        <div class="card card-danger card-outline">
            <div class="card-header">
                <h3 class="card-title">Please input your information</h3>
            </div>
            <div class="card-body">

                @if ($errors->Any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fa fa-warning"></i> Alert!</h5>
                    @foreach ($errors->all() as $error)
                    <p>{{ $error }}</p>
                    @endforeach
                </div>
                @endif
                <form method="POST" action="{{ route('categories.store') }}">
                    @csrf

                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Enter name" name="name">
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" rows="3" pl aceholder="Enter description"
                            name="description"></textarea>
                    </div>
                    <button type="button" class="btn btn-danger">Cencel</button>
                    <button type="Submit" class="btn btn-success float-right">Create</button>

                </form>

            </div>
            <!-- /.card-body -->
        </div>
    </div>
</div>
@endif



<script>
    $(document).ready(function () {
        console.log("hello");

        let spinner = `
            <div class="spinner-border" role="status">
                <span class="sr-only">Loading...</span>
            </div>`;
        $('#form').submit((event) => {
            console.log("hi");

            event.preventDefault()
            let search = $('#search').val()
            console.log(search)
            $('tbody').html(spinner)
            $.ajax({
                url: '{{ route("categories.index") }}',
                method: 'GET',
                data: {
                    search: search
                },
                success: function (results) {
                    console.log(results);
                    // listCategory(results.data)
                    $('tbody').empty().html(results)
                },
                error: function (errors) {
                    console.log(errors);
                }
            })

        })
        // let listCategory = function () {
        // let content = ``
        // for (category of categories) {
        // content += `
        // <tr>
        // <td>${ category.id }</td>
        // <td>${ category.name }</td>
        // <td>${ category.description } </td>
        // <td>
        // <div class="btn-group">
        // <a href="{{ route('categories.show', $category->id) }}" class="btn btn-info">
        // <i class="fa fa-eye"></i>
        // </a>
        // <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-success">
        // <i class="fa fa-edit"></i>
        // </a>
        // <a class="btn btn-danger btn-delete" data-id='{{ $category->id }}'>
        // <i class="fa fa-trash"></i>
        // </a>
        // </div>
        // </td>
        // </tr>
        // `
        // }
        // $('tbody').empty().html(results.data)
        // }

    })

</script>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.master')
@section('title', 'category')
@section('content','Create category')
@section('big-content','home')

@section('header-content')
<div class="row">
    <div class="col-md-6">
        <div class="card card-danger card-outline">
            <div class="card-header">
                <h3 class="card-title">Please input your information</h3>
            </div>
            <div class="card-body">

                @if ($errors->Any())
                <div class="alert alert-warning alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h5><i class="icon fa fa-warning"></i> Alert!</h5>
                    @foreach ($errors->all() as $error)
                    <p>{{ $error }}</p>
                    @endforeach
                </div>
                @endif
                <form method="POST" action="{{ route('categories.update', $category->id) }}">
                    @csrf
                    @method('patch')
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Enter name" name="name"
                            value="{{ $category->name }}">
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" rows="3" placeholder="Enter description"
                            name="description">{{ $category->description }}</textarea>
                    </div>
                    <button type="button" class="btn btn-danger">Cencel</button>
                    <button type="Submit" class="btn btn-success float-right">Save</button>

                </form>

            </div>
            <!-- /.card-body -->
        </div>
    </div>
</div>
@endsection

resources/views/categories/lists.blade.php
@extends('layouts.master')
@section('title', 'category')
@section('content','Lists category')
@section('big-content','home')

@section('header-content')
<div class="row">
    <div class="col-md-12">

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Lists of product</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
                <table class="table table-striped table-bordered">
                    <tbody>
                        <tr>
                            <th style="width: 10px">#</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th style="width: 40px">Action</th>
                        </tr>

                        @if (count($categories)>0)
                        @foreach ($categories as $category)
                        <tr>
                            <td>{{  $category->id }}</td>
                            <td>{{ $category->name }}</td>
                            <td>{{ $category->description }} </td>
                            <td>
                                <div class="btn-group">
                                    <a href="{{ route('categories.show', $category->id) }}" class="btn btn-info ">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                    <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-success">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a data-id='{{ $category->id }}' class="btn btn-danger btn-delete">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        @else()
                        <tr>
                            <td colspan="4">
                                <h2 class="text-center">No Data</h2>
                            </td>
                        </tr>

                        @endif

                    </tbody>
                </table>

            </div>
            <!-- /.card-body -->
            <div class="card-fooler">
                {{ $categories->links() }}
            </div>
        </div>

    </div>
</div>
@push('script')
@if (count($categories)>0)
<script>
    $(document).ready(function () {
        $('.btn-delete').click(function () {
            var id = $(this).data('id');
            var csrf = $('meta[name="csrf-token"]').attr('content');

            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: "{{ route('categories.destroy', $category->id) }}",
                        method: "POST",
                        data: {
                            'id': id,
                            '_method': 'DELETE',
                            '_token': csrf
                        },
                        success: function () {
                            Swal.fire(
                                'Deleted!',
                                'Your file has been deleted.',
                                'success'
                            )
                        },
                        error: function () {
                            console.log('Error');

                        }
                    })
                }
            })
        })
    })

</script>
@endif
@endpush
@endsection

resources/views/categories/result.blade.php
@if (count($categories)>0)

    @foreach ($categories as $category)
    <tr>
        <td>{{  $category->id }}</td>
        <td>{{ $category->name }}</td>
        <td>{{ $category->description }} </td>
        <td>
            <div class="btn-group">
                <a href="{{ route('categories.show', $category->id) }}" class="btn btn-info">
                    <i class="fa fa-eye"></i>
                </a>
                <a href="{{ route('categories.edit', $category->id) }}" class="btn btn-success">
                    <i class="fa fa-edit"></i>
                </a>
                <a class="btn btn-danger btn-delete" data-id='{{ $category->id }}'>
                    <i class="fa fa-trash"></i>
                </a>
            </div>
        </td>
    </tr>
    @endforeach
    
@endif

resources/views/categories/showdata.blade.php
@extends('layouts.master')
@section('title', 'category')
@section('content','Create category')
@section('big-content','home')

@section('header-content')
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card card-danger card-outline">
                <div class="card-header">
                    <h3 class="card-title">Please show data your information</h3>
                </div>
                <div class="card-body">
                    <p>{{ $category->name }}</p>
                    <p>{{ $category->description }}</p>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>
</div>
@endsection