routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::resource('categories', 'CategoryController');
Route::resource('products','ProductController');
Route::resource('orders','OrderController');
Route::resource('orderdetails','OrderDetailController');

Route::get('/', function () { 
    return view('welcome');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    // protected $guarded = [''];
    protected $fillable = [
            'name',
            'code',
            'price',
            'onhand',
            'supplier_name',
            'categories_id',
            'imageurl',
    ];
}
 

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy('id','DESC')->paginate(3);
        return view('products.lists', compact('products'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name'=> '',
            'code'=> '',
            'supplier_name'=>'',
            'category_id'=>'',
            'price'=> '',
            'onhand'=> '',
            'imageurl'=> 'mimes:jpeg,png,jpg,gif,svg|max:2048'
        ]);

        $product =new Product;
        $product->name = $request->name;
        $product->code = $request->code;
        $product->supplier_name = $request->supplier_name;
        $product->category_id = $request->category_id;
        $product->price = $request->price;
        $product->onhand = $request->onhand;
        $path = $request->file('imageurl')->store('uploads/img', 'public');
        $product->imageurl = $path;
        $product->save();
            
        // $products ::create($validated);
        return  redirect()->route('products.index');
        

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product:: findOrFail($id);
        return view('products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        $categories= Category::all();
        $product = Product:: findOrFail($id);
        return view('products.editnew', compact('product','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   
        $validated = $request->validate([
            'name'=> '',
            'code'=> '',
            'supplier_name'=>'',
            'category_id'=>'',
            'price'=> '',
            'onhand'=> '',
            'imageurl'=> 'mimes:jpeg,png,jpg,gif,svg|max:2048'
        ]);
        $product =new Product;
        $product->name = $request->name;
        $product->code = $request->code;
        $product->supplier_name = $request->supplier_name;
        $product->category_id = $request->category_id;
        $product->price = $request->price;
        $product->onhand = $request->onhand;
        $path = $request->file('imageurl')->store('uploads/img', 'public');
        $product->imageurl = $path;
        $product->save();
                
        Product::where('id',$id)->update($validated);
        return redirect()->route('products.index');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        Product::where('id',$reguest->id)->delete();
        return redirect()->route('product.index');
    }
}

resources/views/products/create.blade.php
@extends('layouts.master')
@section('title', 'Ptoducts')
@section('content','Create products')
@section('big-content','home')

@section('header-content')
<form action="{{ route('products.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-md-8">
            <div class="card card-danger card-outline">
                <div class="card-header">
                    <h3 class="card-title">Please input your information</h3>
                </div>
                <div class="card-body">
                    @if ($errors->Any())
                    <div class="alert alert-warning alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fa fa-warning"></i> Alert!</h5>
                        @foreach ($errors->all() as $error)
                        <p>{{ $error }}</p>
                        @endforeach
                    </div>
                    @endif
                    <div class="row form-group">
                        <div class="col-md-4">
                            <input type="text" class="form-control" placeholder="Enter name" name="name">
                        </div>
                        <div class="col-md-4">
                            <input type="text" class="form-control" placeholder="Enter code" name="code">
                        </div>
                        <div class="col-md-4">
                            <input type="text" class="form-control" placeholder="Enter supplier" name="supplier_name">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-4">
                            <select class="form-control" name="category_id">
                                @foreach ($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-4">
                            <input type="text" class="form-control" placeholder="Enter price" name="price">
                        </div>
                        <div class="col-md-4">
                            <input type="text" class="form-control" placeholder="Enter QTY" name="onhand">
                        </div>
                    </div>

                    <button type="button" class="btn btn-danger">Cencel</button>
                    <button type="Submit" class="btn btn-success float-right">Sunmit</button>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-danger card-outline">
                <div class="card-header">
                    <h3 class="card-title">Please Preview</h3>
                </div>
                <div class="card-body">
                    <div class="row form-group">
                        <div class="input-group">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="input-img" name="imageurl">
                                <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12 mt-2 ">
                        <img id="preview" class="img-fluid" src="{{ asset('/img/placeholder.png') }}" alt="placeholder">
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>
</form>

@push('script')
<script>
    $(document).ready(function () {
        $('#input-img').change(function () {
            let img = $('#input-img')[0].files[0]
            let preview = $('#preview')
            let reader = new FileReader;
            if (img) {
                reader.readAsDataURL(img)
            }

            reader.onload = function (e) {
                preview.attr('src', e.target.result)
            }

        })

    })

</script>
@endpush

@endsection

resources/views/products/editnew.blade.php
@extends('layouts.master')
@section('title', 'Update')
@section('content','Update products')
@section('big-content','home')

@section('header-content')
<form method="POST" action="{{ route('products.update', $product->id) }}" enctype="multipart/form-data">
    @csrf
    @method('put')
    <div class="col-md-12">
        <!-- Box Comment -->
        <div class="card card-widget">
            <div class="card-header">
                <div class="user-block">
                    <h6 class="description">Products preview</h6>
                </div>
                <!-- /.user-block -->
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-toggle="tooltip" title="Mark as read">
                        <i class="fa fa-circle-o"></i></button>
                    <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-widget="remove"><i class="fa fa-times"></i>
                    </button>
                </div>
                <!-- /.card-tools -->
            </div>
            <div class="row">
                <div class="card-body col-md-6">
                    <img id="preview" class="img-fluid pad" src="{{ asset('storage'.'/'.$product->imageurl) }}"
                        alt="Photo">

                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="input-img" name="imageurl">
                        <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                    </div>

                </div>
                <div class="col-md-6" style="padding:30px">
                    <div class="card-comment">
                        <div class="row form-group">
                            <div class="col-md-6">
                                Name: <input type="text" class="form-control" placeholder="Enter name" name="name"
                                    value="{{ $product->name }}">
                            </div>
                            <div class="col-md-6">
                                Code:<input type="text" class="form-control" placeholder="Enter code" name="code"
                                    value="{{ $product->code }}">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-md-6">
                                Price:<input type="text" class="form-control" placeholder="Enter price" name="price"
                                    value="{{ $product->price }}">
                            </div>
                            <div class="col-md-6">
                                supplier:<input type="text" class="form-control" placeholder="Enter supplier"
                                    name="supplier_name" value="{{ $product->supplier_name }}">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-md-6">
                                Category:<select class="form-control" name="category_id">
                                    @foreach ($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-6">
                                QTY:<input type="text" class="form-control" placeholder="Enter onhand" name="onhand"
                                    value="{{ $product->onhand }}">
                            </div>
                        </div>
                    </div>
                    <button type="button" class="btn btn-danger">Cencel</button>
                    <button type="Submit" class="btn btn-success float-right">Update</button>
                </div>
            </div>
        </div>
    </div>
</form>

@push('script')
<script>
    $(document).ready(function () {
        $('#input-img').change(function () {
            let img = $('#input-img')[0].files[0]
            let preview = $('#preview')
            let reader = new FileReader;
            if (img) {
                reader.readAsDataURL(img)
            }

            reader.onload = function (e) {
                preview.attr('src', e.target.result)
            }

        })

    })

</script>
@endpush
@endsection

resources/views/products/lists.blade.php
@extends('layouts.master')
@section('title', 'Products')
@section('content','Lists Products')
@section('big-content','home')

@section('header-content')
<div class="row">
    <div class="col-md-12">

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Lists of product</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
                <table class="table table-striped table-bordered">
                    <tbody>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Code</th>
                            <th>Price</th>
                            <th>Onhand</th>
                            <th>Supplier</th>
                            <th>Category</th>
                            <th style="width:150px">Image</th>
                            <th style="width: 40px">Action</th>
                        </tr>

                        @if (count($products)>0)
                        @foreach ($products as $product)
                        <tr>
                            <td>{{  $product->id }}</td>
                            <td>{{ $product->name }}</td>
                            <td>{{ $product->code }} </td>
                            <td>{{ $product->price }} </td>
                            <td>{{ $product->onhand }} </td>
                            <td>{{ $product->supplier_name }} </td>
                            <td>{{ $product->category_id }} </td>
                            <td>
                                <img class="img-fluid" src="{{ asset('storage'.'/'.$product->imageurl) }}" alt="">
                            </td>
                            <td>
                                <div class="btn-group show">
                                    <a href="{{ route('products.show', $product->id) }}" class="btn btn-info">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                    <a href="{{ route('products.edit', $product->id) }}" class="btn btn-success">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a class="btn btn-danger btn-delete" data-id="{{ $product->id }}">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        @else()
                        <tr>
                            <td colspan="4">
                                <h2 class="text-center">No Data</h2>
                            </td>
                        </tr>

                        @endif

                    </tbody>
                </table>

            </div>
            <!-- /.card-body -->
            <div class="card-fooler">
                {{ $products->links() }}
            </div>
        </div>

    </div>
</div>
@push('script')
<script>
    $(document).ready(function () {
        $('.btn-delete').click(function () {
            console.log("hello");
            let id = $(this).data('id');
            console.log(id);

            let csrf = $('meta[name="csrf-token"]').attr('content');
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
S
                    $.ajax({
                        url: "{{ route('products.destroy', $product->id) }}",
                        method: "POST",
                        data: {
                            'id': id,
                            '_method': 'DELETE',
                            '_token': csrf
                        },
                        success: function () {
                            console.log('success');

                        },
                        error: function () {
                            console.log('error');

                        }
                    })
                }
            })

        })

    })

</script>
@endpush
@endsection

resources/views/products/show.blade.php
@extends('layouts.master')
@section('title', 'show')
@section('content','Show productd')
@section('big-content','home')

@section('header-content')
<div class="row">
    <div class="col-md-12">
        <!-- Box Comment -->
        <div class="card card-widget bg-info text-white">
            <div class="card-header">
                <div class="user-block">
                    <h2>Product description</h2>
                </div>
                <!-- /.user-block -->
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-toggle="tooltip" title="Mark as read">
                        <i class="fa fa-circle-o"></i></button>
                    <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-widget="remove"><i class="fa fa-times"></i>
                    </button>
                </div>
                <!-- /.card-tools -->
            </div>
            <div class="row ">
                <div class="col-md-6">
                    <div class="card-body">
                        <img class="img-fluid pad" src="{{ asset('storage'.'/'.$product->imageurl) }}" alt="Photo">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="card-body" style="padding-top:60px">
                        <h6>ID: {{ $product->id }}</h6>
                        <h6>Product name: {{ $product->name }}</h6>
                        <h6>Code: {{ $product->code }}</h6>
                        <h6>Price: {{ $product->price }}</h6>
                        <h6>Onhand: {{ $product->onhand }}</h6>
                        <h6>Supplier: {{ $product->supplier_name }}</h6>
                        <h6>Category ID: {{ $product->category_id }}</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection