routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::resource('categories', 'CategoryController');
Route::resource('products','ProductController');
Route::resource('orders','OrderController');
Route::resource('orderdetails','OrderDetailController');

Route::get('/', function () { 
    return view('welcome');
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $guarded = [''];
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Validator;
use App\Order;


class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::orderBy('id','DESC')->paginate(5);
        return view('orders.lists', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('orders.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validat = $request->validate([
            'name' => 'required|unique:categories|max:150',
            'tel'=>'required',
            'date'=>'required',
            'ship_via'=>'required',
            'ship_price'=>'required',
            'total'=>'required'
        ]);
        Order::create($validat);
        return redirect()->route('orders.index')->with('success','You complete successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $order = Order:: findOrFail($id);
        return view('orders.show', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $order = Order:: findOrFail($id);
        return view('orders.edit', compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validat = $request->validate([
            'name' => '',
            'tel' => '',
            'date'=>'',
            'ship_via'=>'',
            'ship_price'=>'',
            'total'=>''
        ]);
        Order::where('id',$id)->update($validat);
        return redirect()->route('orders.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Order::where('id',$reguest->id)->delete();
        return redirect()->route('orders.index');
    }
}

resources/views/orders/create.blade.php
@extends('layouts.master')
@section('title', 'Orders')
@section('content','Create orders')
@section('big-content','home')

@section('header-content')
<form action="{{ route('orders.store') }}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-md-6" style="margin:auto; margin-top:50px">
            <div class="card card-danger card-outline">
                <div class="card-header">
                    <h3 class="card-title">Please input your information</h3>
                </div>
                <div class="card-body">
                    @if ($errors->Any())
                    <div class="alert alert-warning alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fa fa-warning"></i> Alert!</h5>
                        @foreach ($errors->all() as $error)
                        <p>{{ $error }}</p>
                        @endforeach
                    </div>
                    @endif
                    <div class="row form-group">
                        <div class="col-md-6">
                            Name:<input type="text" class="form-control" placeholder="Enter name" name="name">
                        </div>
                        <div class="col-md-6">
                            Number phone:<input type="text" class="form-control" placeholder="Enter phone" name="tel">
                        </div>

                    </div>
                    <div class="row form-group">
                        <div class="col-md-6">
                            Date:<input type="text" class="form-control" placeholder="Enter date" name="date">
                        </div>
                        <div class="col-md-6">
                            Ship via:<input type="text" class="form-control" placeholder="Enter ship" name="ship_via">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-6">
                            Ship price:<input type="text" class="form-control" placeholder="Enter ship price"
                                name="ship_price">
                        </div>
                        <div class="col-md-6">
                            Total:<input type="text" class="form-control" placeholder="Enter total" name="total">
                        </div>
                    </div>

                    <button type="button" class="btn btn-danger">Cencel</button>
                    <button type="Submit" class="btn btn-success float-right">Create</button>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>


</form>

@endsection

resources/views/orders/edit.blade.php
@extends('layouts.master')
@section('title', 'Orders')
@section('content','Create orders')
@section('big-content','home')

@section('header-content')
<form action="{{ route('orders.update', $order->id) }}" method="POST" enctype="multipart/form-data">
    @csrf
    @method('put')
    <div class="row">
        <div class="col-md-6" style="margin:auto; margin-top:50px">
            <div class="card card-danger card-outline">
                <div class="card-header">
                    <h3 class="card-title">Please input your information</h3>
                </div>
                <div class="card-body">
                    @if ($errors->Any())
                    <div class="alert alert-warning alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fa fa-warning"></i> Alert!</h5>
                        @foreach ($errors->all() as $error)
                        <p>{{ $error }}</p>
                        @endforeach
                    </div>
                    @endif
                    <div class="row form-group">
                        <div class="col-md-6">
                            Name:<input type="text" class="form-control" placeholder="Enter name"
                                name="name" value="{{ $order->name }}">
                        </div>
                        <div class="col-md-6">
                            Number phone:<input type="text" class="form-control" placeholder="Enter phone" name="tel"
                                value="{{ $order->tel }}">
                        </div>

                    </div>
                    <div class="row form-group">
                        <div class="col-md-6">
                            Date:<input type="text" class="form-control" placeholder="Enter date" name="date"
                                value="{{ $order->date }}">
                        </div>
                        <div class="col-md-6">
                            Ship via:<input type="text" class="form-control" placeholder="Enter ship" name="ship_via"
                                value="{{ $order->ship_via }}">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-6">
                            Ship price:<input type="text" class="form-control" placeholder="Enter ship price"
                                name="ship_price" value="{{ $order->ship_price }}">
                        </div>
                        <div class="col-md-6">
                            Total:<input type="text" class="form-control" placeholder="Enter total" name="total"
                                value="{{ $order->total }}">
                        </div>
                    </div>

                    <button type="button" class="btn btn-danger">Cencel</button>
                    <button type="Submit" class="btn btn-success float-right">Update</button>
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>


</form>

@endsection

resources/views/orders/lists.blade.php
@extends('layouts.master')
@section('title', 'Orders')
@section('content','List orders')
@section('big-content','home')

@section('header-content')
<div class="row">
    <div class="col-md-12">

        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Lists of orders</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
                <table class="table table-striped table-bordered">
                    <tbody>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Date</th>
                            <th>Ship via</th>
                            <th>Ship price</th>
                            <th>Total</th>
                            <th>Action</th>
                        </tr>

                        @if (count($orders)>0)
                        @foreach ($orders as $order)
                        <tr>
                            <td>{{  $order->id }}</td>
                            <td>{{ $order->name }}</td>
                            <td>{{ $order->tel }} </td>
                            <td>{{ $order->date }} </td>
                            <td>{{ $order->ship_via }} </td>
                            <td>{{ $order->ship_price }} </td>
                            <td>{{ $order->total }} </td>
                            <td>
                                <div class="btn-group show">
                                    <a href="{{ route('orders.show', $order->id) }}" class=" btn btn-info">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                    <a href="{{ route('orders.edit', $order->id) }}" class=" btn btn-success">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a class="btn btn-danger btn-delete" data-id="{{ $order->id }}">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        @else()
                        <tr>
                            <td colspan="8">
                                <h2 class="text-center">No Data</h2>
                            </td>
                        </tr>

                        @endif

                    </tbody>
                </table>

            </div>
            <!-- /.card-body -->
            <div class="card-fooler">
                {{ $orders->links() }}
            </div>
        </div>

    </div>
</div>
@push('script')
<script>
    $(document).ready(function () {
        $('.btn-delete').click(function () {
            console.log("hello");
            let id = $(this).data('id');
            console.log(id)
            let csrf = $('meta[name="csrf-token"]').attr('content');
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: "{{ route('orders.destroy', $order->id) }}",
                        method: "POST",
                        data: {
                            'id': id,
                            '_method': 'DELETE',
                            '_token': csrf
                        },
                        success: function () {
                            console.log('success');

                        },
                        error: function () {
                            console.log('error');

                        }
                    })
                }
            })

        })

    })

</script>
@endpush
@endsection

resources/views/orders/show.blade.php
@extends('layouts.master')
@section('title', 'show')
@section('content','Show Order')
@section('big-content','home')

@section('header-content')
<div class="row">
    <div class="col-md-6" style="margin:auto; margin-top:50px">
        <!-- Box Comment -->
        <div class="card card-widget bg-info text-white">
            <div class="card-header">
                <div class="user-block">
                    <h2>Product description</h2>
                </div>
                <!-- /.user-block -->
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-toggle="tooltip" title="Mark as read">
                        <i class="fa fa-circle-o"></i></button>
                    <button type="button" class="btn btn-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-widget="remove"><i class="fa fa-times"></i>
                    </button>
                </div>
                <!-- /.card-tools -->
            </div>
            <div class="row ">
                <div class="col-md-12">
                    <div class="card-body">
                        <h6>ID: {{ $order->id }}</h6>
                        <h6>Name: {{ $order->name }}</h6>
                        <h6>Phone: {{ $order->tel }}</h6>
                        <h6>Date: {{ $order->date }}</h6>
                        <h6>Ship via: {{ $order->ship_via }}</h6>
                        <h6>Ship price: {{ $order->ship_price }}</h6>
                        <h6>Total: {{ $order->total }}</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection